### PR TITLE
Commit generated changes to diagnostics prefab

### PR DESCRIPTION
**Pull request by FejZa**
## Overview

So... that diagnostics window prefab bug still exists. These are the changes Unity generates for some reason without me even touching that prefab. Can anyone make up their mind about this? Is it worth trying to get those merged and see if Unity is finally happy with it?

### CODE REVIEW

**Comment by StephenHodgson** [comment]
It's mainly just from being re-serialized when imported.

I have a feeling it's bc of the text mesh pro assets used in the prefab.

**Comment by FejZa** [comment]
True, I am also looking at TMP here. But still I think it should not happen in this way. I mean MRTK has a lot of TMP prefabs doesn't it? Can't remember I'seen these serialization changes happeing over there. Really frustrating since it prevents the projct from building.

**Comment by FejZa** [comment]
With the changes of this PR applied my build succeeds at least.

**Comment by FejZa** [comment]
Nevermind. The same issue reappered even with these changes applied. It keeps regenerating them.

**Pull request closed without merging**
