### PR TITLE
Oculus Quest Open vr

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
## Overview

Updating default profiles to include Oculus Quest controllers

### CODE REVIEW

**Comment by FejZa** [comment]
Go Simon, go Simon. I need this 😋

**Comment by SimonDarksideJ** [comment]
It's "Working" @FejZa but the pointers aren't activating. Still trying to figure out why.

*Note
This version will allow you to sideload to Quest.  For Store application you'll need the native version, which I'm already working on

**Comment by wassx** [comment]
Is this PR still relevant when the native support is done?

**Comment by StephenHodgson** [comment]
Are we still using this branch?

**Pull request closed without merging**
