### PR TITLE
Rename HandBoundsMode to HandBoundsLOD for better understanding

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Please see https://github.com/XRTK/XRTK-Core/pull/677

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I believe we need to update to the new xrtk.core upm preview version and this should be good to go

**Comment by FejZa** [comment]
You mean updating the Core module commit? Or do we have to actually release the preview package for the checks to work?

**Comment by StephenHodgson** [comment]
I meant to update the preview package in upm

**Comment by StephenHodgson** [comment]
The preview release is already out, so just need to go into the unity package manager and update it in the project manifest

**Comment by FejZa** [comment]
Sorry but I am a bit confused here. In which project do I have to update the Core preview package?

**Comment by StephenHodgson** [comment]
The SDK Project

**Comment by FejZa** [comment]
Ah I see. Never ever opened up any of the submodule projects and didn't think about them.

**Comment by FejZa** [comment]
So far I thought they are useless.

**Comment by StephenHodgson** [comment]
No worries, it is only needed if there is breaking change from upstream

**Comment by StephenHodgson** [comment]
Lol they're aren't useless. You can open either as part of core (which pulls in all the projects), or open each individually. It really doesn't matter. It's just much easier to work in the core project when you're doing breaking changes or working on core functionality and want to update across all packages.

**Comment by StephenHodgson** [comment]
If you're working on platform specific stuff you could stick to a single project.

**Review by StephenHodgson — APPROVED** [review]

**Comment by StephenHodgson** [comment]
Once tests pass we can merge

**Pull request merged**
