### PR TITLE
Removing non core profiles from the Default profiles to avoid corruption

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
## Overview

Corresponding SDK PR to remove profiles that are broken as they are not part of core. These should be added by the platform when imported

This is centered around the work in the following core PR which will move profiles for non-core configuration to their respective package, e.g. Oculus, Lumin, WMR
https://github.com/XRTK/XRTK-Core/pull/433

Those packages will prompt the user to add the configuration if not configured for use.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I'm not sure I agree with this change, as the default profiles are all included in the sdk, not the core.

Can you explain this problem a bit more?

**Comment by SimonDarksideJ** [comment]
In short, If you add the SDK to your project without dependant projects loaded (Oculus / Lumin / WMR) then any Core profile using those dependencies becomes corrupted.
In 2019.1 and below, this corruption only happened when you hit configure, so you could load all the projects before use.  In 2019.2+ with the new Asset Database however, this is done on import.

In short, you are left with a situation with invalid configuration.

The better answer, is for each platform to add it's own defaults when loaded to avoid complication

**Comment by StephenHodgson** [comment]
So there's other PRs that are blocking this one that implement this autoloading?

**Comment by SimonDarksideJ** [comment]
The Profile validation PR's will ultimately load the configuration on request, moving the default profiles for those systems into their respective packages.
https://github.com/XRTK/XRTK-Core/pull/433

**Comment by StephenHodgson** [comment]
Please be sure to reference any blocking or associated PRs in the overview above.

**Comment by SimonDarksideJ** [comment]
Deleting this PR until the mappings work (#150) is done and re-evaluating

**Pull request closed without merging**
