### PR TITLE
Fix default Data providers profile for WMR

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
## Overview

Fix default Data providers profile for WMR

## Changes:

- Resolves: #136

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@FejZa I know you recently updated this. Can you also verify this change is correct as well please?

**Comment by FejZa** [comment]
See https://github.com/XRTK/WindowsMixedReality/blob/development/XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/Controllers/WindowsMixedRealityControllerDataProvider.cs

**Comment by FejZa** [comment]
The issue here that the required fix in WMR hasn't been released yet it seems. The released WMR package still comes with the old `WindowsMixedRealityDataProvider`

**Comment by FejZa** [comment]
Yep, XRTK/WMR is at v0.1.9 but I bumped it to v0.1.10 because of the breaking changes. So the actual fix is here to make a new WMR release and update the SDK dependancy to required WMR v.0.1.10 at least.

**Comment by StephenHodgson** [comment]
Thanks. I thought so but needed to verify.

**Comment by SimonDarksideJ** [comment]
So the question is @StephenHodgson / @FejZa which is the correct path?  This PR is to fix what is currently in Live as it is broken:
* if there is a WMR fix that will resolve the situation, should that be the resolution
* Or do we need this change to fix the profiles

**Comment by SimonDarksideJ** [comment]
On hold for testing with a new WMR release

**Comment by SimonDarksideJ** [comment]
Resolved by releasing a new version of the WMR package

**Comment by StephenHodgson** [comment]
> we must ensure we loop such things together to avoid such occurrences in the production UPM packages and highlight if dependant changes are needed

That's why we're supposed to link the changes together using either the issue or PR link

**Pull request closed without merging**
