### PR TITLE
Feature/diagnostics system console

### PR DESCRIPTION
**Pull request by FejZa**
## Overview

Please use https://github.com/XRTK/XRTK-Core/pull/422 for discussion and overview.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Could you do me a favor and update the speech commands profile with actions set to `None` or something that makes more sense please? I noticed they were kinda strange the other day.

**Comment by FejZa** [comment]
I did. Also set the KeyCodes to none, because they currently also don't make any sense. Those default speech commands need a revision I think because if they are there they should also function by default.

**Comment by FejZa** [comment]
@StephenHodgson the SDK PR validation keeps failing in the license activation step. Any ideas what's going on?

**Comment by StephenHodgson** [comment]
It's bc there's a breaking change in the core that needs a release before it'll pass. I don't mind ignoring it for now.

**Comment by StephenHodgson** [comment]
See https://github.com/XRTK/XRTK-Core/pull/428

Once that gets merged and a new release then the compiler errors will go away.

It's not an issue with licensing

**Comment by FejZa** [comment]
alright. I just checked in DevOps and the step that failed was about license activation. But sounds like you got the plan 🙂

**Comment by StephenHodgson** [comment]
That was the step it failed on but the logs say it was a compiler error.

Likely from the breaking changes in the PR I specified above.

**Pull request merged**
