### PR TITLE
Release 0.2.2

### PR DESCRIPTION
**Pull request by StephenHodgson**

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Please do not squash this PR

**Comment by FejZa** [comment]
How did this one get merged? Just curious. Can't we disable squasing for the master branch?

**Comment by StephenHodgson** [comment]
We can't disable a branching strategy per branch.

**Comment by StephenHodgson** [comment]
> How did this one get merged?

I merged it, after I tested it.

**Pull request merged**
